// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/order_service/order_mutation"
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"github.com/pdcgo/tracking_service"
	"github.com/pdcgo/tracking_service/thirdparties"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	defaultClientInterceptor, err := custom_connect.NewDefaultClientInterceptor()
	if err != nil {
		return nil, err
	}
	trackingServiceClient := NewTrackingClient(appConfig, defaultClientInterceptor)
	checkOrderFunc := NewCheckOrder(db, trackingServiceClient)
	serveMux := http.NewServeMux()
	registerReflectFunc := custom_connect.NewRegisterReflect(serveMux)
	cache, err := NewCache(appConfig)
	if err != nil {
		return nil, err
	}
	authorization := NewAuthorization(appConfig, db, cache)
	nextFuncParam := thirdparties.NewMultipleTracker(appConfig)
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	orderTagMutation := order_mutation.NewTagMutation(db)
	registerHandler := tracking_service.NewRegister(serveMux, db, authorization, nextFuncParam, defaultInterceptor, orderTagMutation)
	apiFunc := NewApi(serveMux, registerReflectFunc, registerHandler)
	app := NewApp(checkOrderFunc, apiFunc)
	return app, nil
}
